// Bộ 500 Prompt AI Kiếm Tiền — dữ liệu nội dung
// Chia thành 7 nhóm: Video AI, Kịch bản, Hook, Tạo ảnh, Review sản phẩm,
// Shopee Affiliate, TikTok. Placeholder dạng [ ... ] để người dùng tự điền.

export type PromptCategory = {
  slug: string;
  title: string;
  emoji: string;
  desc: string;
  prompts: string[];
};

const videoAI: string[] = [
  "Viết prompt cho AI tạo video (Runway/Kling/Veo) mô tả cảnh mở đầu 5 giây thu hút cho sản phẩm [sản phẩm]: bối cảnh, ánh sáng, chuyển động camera, cảm xúc.",
  "Tạo kịch bản shot-by-shot cho video quảng cáo AI 15 giây về [sản phẩm], mỗi cảnh ghi rõ prompt hình ảnh, thời lượng và câu thoại.",
  "Viết prompt tạo video AI phong cách cinematic quảng bá [thương hiệu], tông màu ấm, chuyển động camera slow-motion, tỉ lệ 9:16.",
  "Sinh 5 biến thể prompt video AI cho cùng một cảnh 'người dùng mở hộp [sản phẩm]' với 5 phong cách khác nhau: tối giản, sang trọng, năng động, hài hước, đời thường.",
  "Viết prompt tạo video AI dạng before/after cho [dịch vụ], nhấn mạnh sự thay đổi rõ rệt, có text overlay và nhạc nền gợi ý.",
  "Tạo prompt video AI mô phỏng review khui hộp (unboxing) [sản phẩm] góc quay POV, tay cầm sản phẩm, nền bàn gỗ, ánh sáng tự nhiên.",
  "Viết prompt tạo video AI hoạt hình 2D giải thích cách hoạt động của [sản phẩm] trong 20 giây, phong cách flat design, màu tươi sáng.",
  "Sinh prompt video AI b-roll chất lượng cao cho ngành [ngành hàng] để chèn vào TikTok/Reels: 10 cảnh ngắn 3 giây, mô tả chi tiết từng cảnh.",
  "Viết prompt video AI dạng talking head người mẫu ảo giới thiệu [sản phẩm], biểu cảm tự nhiên, khẩu hình khớp lời thoại tiếng Việt.",
  "Tạo prompt video AI theo trend 'một ngày của...' để lồng ghép [sản phẩm] vào đời sống thường ngày, 8 phân cảnh liên tiếp.",
  "Viết prompt video AI quảng cáo món ăn [món ăn]: cận cảnh hơi nóng bốc lên, phô mai kéo sợi, ánh sáng vàng, chuyển động 120fps.",
  "Sinh prompt video AI phong cách du lịch quảng bá [địa điểm/dịch vụ], drone shot, bình minh, màu teal & orange, nhạc epic.",
  "Viết prompt tạo video AI dạng testimonial khách hàng ảo kể trải nghiệm dùng [sản phẩm], ngồi trong quán cafe, ánh sáng mềm.",
  "Tạo prompt video AI mô phỏng ASMR sử dụng [sản phẩm]: âm thanh chi tiết, cận cảnh, chuyển động chậm, không lời thoại.",
  "Viết prompt video AI 'stop motion' cho [sản phẩm] với các vật thể tự sắp xếp, nền pastel, nhịp điệu vui nhộn.",
  "Sinh prompt video AI quảng cáo thời trang [sản phẩm thời trang]: người mẫu catwalk, đèn studio, phông nền gradient, chuyển cảnh nhanh theo beat.",
  "Viết prompt video AI dạng 'trước khi mua vs sau khi mua' [sản phẩm], chia đôi màn hình, biểu cảm đối lập.",
  "Tạo prompt video AI hiệu ứng zoom vô hạn (infinite zoom) dẫn dắt vào [thương hiệu], siêu thực, màu neon.",
  "Viết prompt video AI mô phỏng góc quay flatlay xoay 360 độ trưng bày bộ [sản phẩm], nền cẩm thạch, đèn dịu.",
  "Sinh prompt video AI kể chuyện thương hiệu (brand story) 30 giây cho [thương hiệu], 3 hồi: vấn đề — giải pháp — kết quả.",
  "Viết prompt video AI theo phong cách retro thập niên 90 quảng bá [sản phẩm], hạt film, màu ám vàng, chữ VHS.",
  "Tạo prompt video AI 'sản phẩm bay lơ lửng' (levitation) trong không gian tối, tia sáng viền, khói nhẹ, dành cho [sản phẩm].",
  "Viết prompt video AI mô tả cảnh thiên nhiên hùng vĩ mở màn cho quảng cáo [sản phẩm], sau đó cắt về sản phẩm cận cảnh.",
  "Sinh prompt video AI dạng meme động hài hước cho [sản phẩm] bám trend, có nhân vật biểu cảm cường điệu.",
  "Viết prompt video AI quảng cáo mỹ phẩm [sản phẩm]: giọt serum rơi chậm, kết cấu mịn, làn da rạng rỡ, macro shot.",
  "Tạo prompt video AI 'người máy/AI tương lai' giới thiệu công nghệ của [sản phẩm], giao diện hologram, xanh dương neon.",
  "Viết prompt video AI dạng recipe tua nhanh (time-lapse) chế biến [món ăn] có dùng [sản phẩm], góc top-down.",
  "Sinh prompt video AI so sánh kích thước/tỉ lệ để làm nổi bật đặc điểm của [sản phẩm], hiệu ứng thị giác bất ngờ.",
  "Viết prompt video AI cảnh mưa/đêm thành phố lung linh làm nền cảm xúc cho câu chuyện về [thương hiệu].",
  "Tạo prompt video AI mô phỏng người dùng thật quay bằng điện thoại (UGC style) trải nghiệm [sản phẩm], rung nhẹ, chân thực.",
  "Viết prompt video AI hoạt hình nhân vật linh vật (mascot) của [thương hiệu] nhảy múa theo nhạc, dễ thương.",
  "Sinh prompt video AI dạng countdown khuyến mãi 'chỉ còn 3-2-1' cho chương trình sale của [thương hiệu], năng lượng cao.",
  "Viết prompt video AI cận cảnh chất liệu (texture) của [sản phẩm]: vải, da, kim loại, gỗ — nhấn mạnh sự cao cấp.",
  "Tạo prompt video AI mô phỏng phòng gym/thể thao để quảng bá [sản phẩm thể thao], mồ hôi, năng lượng, cắt nhanh theo beat.",
  "Viết prompt video AI dạng 'sản phẩm giải quyết nỗi đau': cảnh 1 khó chịu — cảnh 2 dùng [sản phẩm] — cảnh 3 thoải mái.",
  "Sinh prompt video AI khung cảnh Giáng Sinh/Tết ấm cúng lồng ghép quà tặng [sản phẩm], đèn lung linh, tuyết/hoa mai.",
  "Viết prompt video AI POV lái xe/du lịch để đặt [sản phẩm] vào bối cảnh phiêu lưu, hoàng hôn, tự do.",
  "Tạo prompt video AI 'giải phẫu sản phẩm' tách lớp từng bộ phận của [sản phẩm] bay ra, nền trắng studio.",
  "Viết prompt video AI mô phỏng livestream bán hàng ảo cho [sản phẩm], có comment chạy, hiệu ứng tim, giỏ hàng.",
  "Sinh prompt video AI theo phong cách phim tài liệu ngắn về nguồn gốc/nguyên liệu của [sản phẩm], giọng kể trầm ấm.",
  "Viết prompt video AI hiệu ứng 'morphing' biến hình từ vấn đề thành giải pháp [sản phẩm], mượt mà, siêu thực.",
  "Tạo prompt video AI mô tả 6 cảnh chuyển tiếp (transition) sáng tạo để ghép clip sản phẩm [sản phẩm] mượt mà.",
  "Viết prompt video AI quảng cáo đồ uống [đồ uống]: đá rơi, bọt sủi, giọt nước đọng trên ly, ánh sáng ngược.",
  "Sinh prompt video AI dạng 'ranking top sản phẩm' cho [ngành hàng] với animation số thứ hạng nhảy lên.",
  "Viết prompt video AI cảnh gia đình sum vầy sử dụng [sản phẩm gia dụng], ấm áp, ánh sáng golden hour.",
  "Tạo prompt video AI phong cách anime giới thiệu [sản phẩm] cho tệp khách trẻ, màu rực rỡ, hiệu ứng tốc độ.",
  "Viết prompt video AI 'sản phẩm khổng lồ' đặt giữa thành phố (surreal scale) để gây chú ý cho [thương hiệu].",
  "Sinh prompt video AI dạng tutorial 'cách dùng [sản phẩm] trong 3 bước', mỗi bước 1 cảnh rõ ràng, có số thứ tự.",
  "Viết prompt video AI cảnh phòng làm việc hiện đại tối giản đặt [sản phẩm công nghệ], tông xám xanh, chuyên nghiệp.",
  "Tạo prompt video AI dạng 'oddly satisfying' với [sản phẩm]: các chuyển động lặp lại thỏa mãn thị giác.",
  "Viết prompt video AI quảng cáo khóa học/dịch vụ số [dịch vụ]: người thành công, biểu đồ tăng trưởng, năng lượng tích cực.",
  "Sinh prompt video AI cảnh underwater (dưới nước) sang trọng làm nổi bật tính năng chống nước của [sản phẩm].",
  "Viết prompt video AI mô phỏng góc quay macro côn trùng/thiên nhiên ẩn dụ cho đặc tính [sản phẩm].",
  "Tạo prompt video AI dạng split-screen so sánh [sản phẩm A] vs [sản phẩm B] để làm nổi bật ưu điểm.",
  "Viết prompt video AI hiệu ứng particle (hạt) tụ lại thành logo [thương hiệu] ở cuối clip, hoành tráng.",
  "Sinh prompt video AI phong cách vintage film Nhật (Ghibli-like) kể câu chuyện dịu dàng về [thương hiệu].",
  "Viết prompt video AI cảnh chợ/phố ẩm thực Việt Nam sống động để quảng bá [món ăn/đặc sản].",
  "Tạo prompt video AI mô phỏng người thật cầm điện thoại quay góc gương (mirror selfie) khoe [sản phẩm thời trang].",
  "Viết prompt video AI dạng 'câu hỏi gây tò mò' mở đầu 3 giây rồi mới lộ [sản phẩm], giữ chân người xem.",
  "Sinh prompt video AI cảnh phòng ngủ cozy ban đêm để quảng bá [sản phẩm chăm sóc giấc ngủ], ánh đèn ấm.",
  "Viết prompt video AI hiệu ứng glitch/cyberpunk cho [sản phẩm công nghệ], neon tím-xanh, chuyển động giật.",
  "Tạo prompt video AI dạng 'thử thách 24h dùng [sản phẩm]' với 4 mốc thời gian, mỗi mốc 1 cảnh.",
  "Viết prompt video AI cảnh salon/spa thư giãn để quảng bá [dịch vụ làm đẹp], hơi nước, nến, tông trắng-be.",
  "Sinh prompt video AI mô tả 5 cảnh lifestyle đa dạng lứa tuổi cùng dùng [sản phẩm], truyền tải 'ai cũng phù hợp'.",
  "Viết prompt video AI cảnh khai trương/sự kiện có pháo giấy, đèn sân khấu để giới thiệu [thương hiệu/cửa hàng].",
  "Tạo prompt video AI dạng 'hôm nay tôi làm được gì với [sản phẩm]', phong cách vlog năng động cận cảnh.",
  "Viết prompt video AI cảnh bàn tiệc/nấu ăn sang trọng để đặt [sản phẩm ẩm thực] làm trung tâm, plating đẹp.",
  "Sinh prompt video AI hiệu ứng chuyển mùa (4 mùa) trong 1 khung hình để kể độ bền của [sản phẩm].",
  "Viết prompt video AI mô phỏng bảng tin/mạng xã hội cuộn qua để dừng lại ở quảng cáo [sản phẩm], meta & bắt trend.",
  "Tạo prompt video AI cảnh học sinh/sinh viên học tập hiệu quả nhờ [sản phẩm giáo dục], tươi sáng, truyền cảm hứng.",
  "Viết prompt video AI dạng 'phản ứng bất ngờ' của người dùng khi lần đầu thấy hiệu quả [sản phẩm], biểu cảm wow.",
  "Sinh prompt video AI cảnh thú cưng đáng yêu tương tác với [sản phẩm thú cưng], vui nhộn, dễ viral.",
  "Viết prompt video AI hoành tráng dạng trailer điện ảnh 20 giây ra mắt [sản phẩm], build-up căng thẳng rồi bùng nổ.",
  "Tạo prompt video AI mô tả đầy đủ thông số (aspect ratio, fps, độ dài, style, camera, lighting, mood) chuẩn để nạp vào công cụ video AI cho [sản phẩm].",
  "Viết prompt video AI dạng 'lời khuyên nhanh 5 giây' của chuyên gia ảo về [ngành hàng], gọn, uy tín, kèm CTA.",
];

const script: string[] = [
  "Viết kịch bản video TikTok 30 giây bán [sản phẩm] theo cấu trúc Hook — Vấn đề — Giải pháp — CTA, chia rõ từng cảnh và lời thoại.",
  "Viết kịch bản quảng cáo 60 giây cho [sản phẩm] theo công thức AIDA (Attention — Interest — Desire — Action), giọng văn gần gũi.",
  "Tạo kịch bản video review [sản phẩm] dài 45 giây gồm: mở đầu gây tò mò, 3 điểm nổi bật, 1 nhược điểm nhỏ, chốt mua.",
  "Viết kịch bản dạng storytelling cá nhân 'tôi từng gặp vấn đề [vấn đề] cho đến khi biết [sản phẩm]', chân thực, cảm xúc.",
  "Viết kịch bản video so sánh [sản phẩm A] và [sản phẩm B], khách quan, kết luận nên chọn cái nào cho từng nhu cầu.",
  "Tạo kịch bản video 'Top 5 lý do bạn nên mua [sản phẩm]' đếm ngược từ 5 về 1, mỗi lý do 1 cảnh nhanh.",
  "Viết kịch bản livestream bán [sản phẩm] 3 phút: chào — giới thiệu — demo — xử lý phản đối — chốt đơn — thúc giục.",
  "Viết kịch bản video dạng 'sự thật ít ai nói về [ngành hàng]' để tạo uy tín trước khi giới thiệu [sản phẩm].",
  "Tạo kịch bản video 15 giây theo trend [trend] nhưng khéo léo lồng [sản phẩm], giữ nhịp nhanh, punchline cuối.",
  "Viết kịch bản video hướng dẫn 'cách dùng [sản phẩm] đúng cách' 3 bước, mỗi bước có lời thoại và hành động.",
  "Viết kịch bản video 'trước — sau' cho [dịch vụ], nhấn vào cảm xúc thất vọng trước và hài lòng sau.",
  "Tạo kịch bản video FAQ trả lời 3 câu hỏi thường gặp về [sản phẩm], mỗi câu 10 giây, súc tích.",
  "Viết kịch bản video 'unboxing + first impression' [sản phẩm], mô tả cảm giác khi mở, chất lượng, giá trị.",
  "Viết kịch bản dạng hội thoại 2 nhân vật (người hoài nghi & người đã dùng) về [sản phẩm], tự nhiên, thuyết phục.",
  "Tạo kịch bản video 'một ngày của tôi cùng [sản phẩm]' lồng ghép sản phẩm vào các khoảnh khắc thường ngày.",
  "Viết kịch bản video bóc phốt/cảnh báo 'đừng mua [ngành hàng] khi chưa biết điều này' rồi dẫn tới [sản phẩm] tốt.",
  "Viết kịch bản video quảng cáo cảm xúc về [thương hiệu] hướng tới dịp [dịp lễ], kết bằng thông điệp ý nghĩa.",
  "Tạo kịch bản video dạng 'thử thách 7 ngày dùng [sản phẩm]' với nhật ký từng ngày và kết quả bất ngờ.",
  "Viết kịch bản video 'giải mã tại sao [sản phẩm] hot', phân tích 3 yếu tố khiến ai cũng muốn mua.",
  "Viết kịch bản video ngắn 20 giây theo phong cách hài hước/skit tình huống có [sản phẩm] giải cứu.",
  "Tạo kịch bản video 'review thật, không PR' về [sản phẩm]: ưu, nhược, ai nên mua, ai không nên.",
  "Viết kịch bản video quảng cáo dạng ẩn dụ/so sánh sáng tạo cho [sản phẩm] (ví dụ: nhanh như..., bền như...).",
  "Viết kịch bản video giáo dục 'điều bạn chưa biết về [chủ đề]' để nuôi tệp khách trước khi bán [sản phẩm].",
  "Tạo kịch bản video testimonial khách hàng: bối cảnh — vấn đề — giải pháp [sản phẩm] — kết quả cụ thể bằng số.",
  "Viết kịch bản video flash sale khẩn cấp cho [sản phẩm]: nhấn số lượng có hạn, ưu đãi, đồng hồ đếm ngược.",
  "Viết kịch bản video 'câu chuyện thương hiệu' 90 giây: khởi nguồn — sứ mệnh — sản phẩm — lời mời đồng hành.",
  "Tạo kịch bản video dạng 'nếu bạn đang [tình huống], hãy xem hết clip này', giữ chân bằng lời hứa giá trị.",
  "Viết kịch bản video mini-vlog 'lý do tôi chuyển sang dùng [sản phẩm]', chân thực như tâm sự với bạn.",
  "Viết kịch bản video 'phá bỏ 3 lầm tưởng về [ngành hàng]' để định vị [sản phẩm] là lựa chọn thông minh.",
  "Tạo kịch bản video theo cấu trúc PAS (Problem — Agitate — Solution) cho [sản phẩm], khoét sâu nỗi đau rồi giải quyết.",
  "Viết kịch bản video dạng 'checklist trước khi mua [ngành hàng]', kết bằng gợi ý [sản phẩm] đáp ứng đủ.",
  "Viết kịch bản video 'khách hỏi — tôi đáp' xử lý phản đối phổ biến về giá/chất lượng của [sản phẩm].",
  "Tạo kịch bản video 30 giây cho [dịch vụ] B2B: nêu bài toán doanh nghiệp — giải pháp — kết quả ROI.",
  "Viết kịch bản video 'mở hộp quà tặng [sản phẩm]' cho dịp [dịp], gợi ý lý do đây là món quà hoàn hảo.",
  "Viết kịch bản video reaction 'tôi đã thử [sản phẩm] viral trên TikTok và đây là sự thật'.",
  "Tạo kịch bản video 'so găng giá': tại sao [sản phẩm] đắt hơn nhưng vẫn đáng tiền, phân tích giá trị dài hạn.",
  "Viết kịch bản video 'hướng dẫn chọn [ngành hàng] theo nhu cầu', phễu dẫn về [sản phẩm] phù hợp nhất.",
  "Viết kịch bản video 15 giây bắt trend nhạc/điệu nhảy đang hot, chèn [sản phẩm] một cách tự nhiên.",
  "Tạo kịch bản video 'khoảnh khắc aha': người dùng phát hiện tính năng ẩn tuyệt vời của [sản phẩm].",
  "Viết kịch bản video kể chuyện khách hàng khó tính bị [sản phẩm] chinh phục thế nào.",
  "Viết kịch bản video 'behind the scenes' quá trình làm ra [sản phẩm], tạo niềm tin về chất lượng.",
  "Tạo kịch bản video dạng 'đừng lướt qua nếu bạn [đặc điểm khách hàng]', cá nhân hóa để giữ chân.",
  "Viết kịch bản video 'chi tiết nhỏ nhưng đắt giá' của [sản phẩm] mà người bán khác không nói.",
  "Viết kịch bản video 'tôi tiết kiệm được [X] nhờ [sản phẩm]', dùng con số cụ thể để thuyết phục.",
  "Tạo kịch bản video call-to-action mạnh mẽ cuối phễu: ưu đãi, bảo hành, đổi trả, lý do mua ngay hôm nay.",
  "Viết kịch bản video 'phản hồi bình luận': trả lời một comment nghi ngờ về [sản phẩm] một cách khéo léo.",
  "Viết kịch bản video 'so sánh tôi của trước và sau khi dùng [sản phẩm]', hành trình chuyển đổi rõ rệt.",
  "Tạo kịch bản video dạng danh sách 'X điều tôi ước biết sớm hơn về [chủ đề]', chèn [sản phẩm] ở điểm cao trào.",
  "Viết kịch bản video quảng cáo mùa vụ (Tết/Hè/Back to school) cho [sản phẩm], gắn với nhu cầu theo mùa.",
  "Viết kịch bản video 'thử tin đồn': kiểm chứng một lời đồn về [sản phẩm/ngành hàng] và đưa ra kết luận.",
  "Tạo kịch bản video 'combo tiết kiệm': gợi ý mua kèm [sản phẩm A] + [sản phẩm B] để tối ưu giá trị.",
  "Viết kịch bản video hướng đối tượng người mới bắt đầu với [chủ đề], hạ thấp rào cản, dẫn tới [sản phẩm] dễ dùng.",
  "Viết kịch bản video 'tại sao ai cũng đang nói về [sản phẩm]', tạo hiệu ứng FOMO xã hội.",
  "Tạo kịch bản video dạng 'nhật ký kết quả sau 30 ngày dùng [sản phẩm]', có mốc tuần 1-2-3-4.",
  "Viết kịch bản video ngắn cho quảng cáo Facebook/Reels 6 giây (bumper), 1 thông điệp duy nhất về [sản phẩm].",
  "Viết kịch bản video 'giải thích trong 30 giây': [sản phẩm] hoạt động thế nào cho người chưa từng biết.",
  "Tạo kịch bản video 'top sai lầm khi dùng [ngành hàng]' và cách [sản phẩm] khắc phục.",
  "Viết kịch bản video sự kiện ra mắt sản phẩm mới, tạo cảm giác trọng đại và khan hiếm cho [sản phẩm].",
  "Viết kịch bản video 'phỏng vấn nhanh trên phố' người dùng nói cảm nhận về [sản phẩm], chân thực đa dạng.",
  "Tạo kịch bản video hướng dẫn tận dụng ưu đãi/mã giảm giá khi mua [sản phẩm], rõ ràng từng bước.",
  "Viết kịch bản video 'điều gì xảy ra nếu bạn không dùng [sản phẩm]', khắc họa hệ quả để tạo động lực.",
  "Viết kịch bản video định vị cao cấp cho [sản phẩm], ngôn ngữ sang trọng, nhấn vào đẳng cấp và trải nghiệm.",
  "Tạo kịch bản video ngắn dạng 'tips & hack' liên quan [chủ đề] mà [sản phẩm] hỗ trợ, giá trị trước bán sau.",
  "Viết kịch bản video 'khách hàng thân thiết chia sẻ': loyalty story tăng độ tin cậy cho [thương hiệu].",
  "Viết kịch bản video giải quyết một nỗi sợ mua hàng online (hàng giả, không giống hình...) cho [sản phẩm].",
  "Tạo kịch bản video 'thử thách người thân/bạn bè dùng [sản phẩm]' và ghi lại phản ứng thật.",
  "Viết kịch bản video cho ngành F&B: mô tả trải nghiệm vị giác của [món ăn/đồ uống] khiến người xem thèm.",
  "Viết kịch bản video 'lời khuyên từ chuyên gia' 30 giây, mượn uy tín chuyên môn để giới thiệu [sản phẩm].",
  "Tạo kịch bản video 'so sánh mua ngoài tiệm vs mua [sản phẩm]', làm nổi bật tiện lợi và tiết kiệm.",
  "Viết kịch bản video theo mô hình 4U (Useful — Urgent — Unique — Ultra-specific) cho quảng cáo [sản phẩm].",
  "Viết kịch bản video 'tổng kết cuối clip' tóm tắt 3 lý do mua và 1 CTA duy nhất cho [sản phẩm].",
  "Tạo kịch bản video khơi gợi tò mò kiểu 'bí mật mà người bán [ngành hàng] không muốn bạn biết'.",
  "Viết kịch bản video hài tình huống công sở/gia đình có [sản phẩm] xuất hiện đúng lúc, tự nhiên và vui.",
  "Viết kịch bản video 'tôi đã sai khi nghĩ [sản phẩm] không cần thiết', hành trình đổi ý thuyết phục.",
  "Tạo kịch bản video ngắn tối ưu cho quảng cáo trả phí: 3 giây đầu chặn ngón tay, giữa cung cấp giá trị, cuối CTA về [sản phẩm].",
];

const hook: string[] = [
  "Viết 10 câu hook mở đầu 3 giây gây sốc/tò mò cho video bán [sản phẩm] trên TikTok.",
  "Tạo 10 hook dạng câu hỏi khiến người xem phải dừng lại cho nội dung về [chủ đề].",
  "Viết 10 hook dạng 'con số gây bất ngờ' (VD: 90% mọi người...) cho [ngành hàng].",
  "Sinh 10 hook khơi gợi nỗi đau/vấn đề mà [sản phẩm] giải quyết, viết ở ngôi 'bạn'.",
  "Viết 10 hook dạng 'đừng làm X nếu chưa biết Y' liên quan tới [chủ đề].",
  "Tạo 10 hook tạo FOMO (sợ bỏ lỡ) cho chương trình khuyến mãi [sản phẩm].",
  "Viết 10 hook dạng lời hứa kết quả (VD: 'sau video này bạn sẽ...') cho nội dung [chủ đề].",
  "Sinh 10 hook gây tranh cãi nhẹ (controversial) để tăng bình luận cho chủ đề [chủ đề].",
  "Viết 10 hook dạng 'bí mật/sự thật ít ai nói' về [ngành hàng].",
  "Tạo 10 hook cá nhân hóa nhắm đúng tệp '[chân dung khách hàng]'.",
  "Viết 10 hook dạng 'trước khi mua [sản phẩm], xem hết clip này'.",
  "Sinh 10 hook so sánh 'cái này vs cái kia' để mở đầu video về [sản phẩm].",
  "Viết 10 hook dạng câu chuyện 'tôi đã từng...' để dẫn vào [sản phẩm].",
  "Tạo 10 hook tận dụng sự tò mò về kết quả (curiosity gap) cho video [chủ đề].",
  "Viết 10 hook dạng cảnh báo 'sai lầm phổ biến khi [hành động]'.",
  "Sinh 10 hook dùng trend/câu nói đang viral, gắn với [sản phẩm].",
  "Viết 10 hook dạng liệt kê 'X thứ bạn nên biết về [chủ đề]'.",
  "Tạo 10 hook gợi cảm xúc mạnh (tiếc nuối, ghen tị, tự hào) quanh [sản phẩm].",
  "Viết 10 hook dạng 'nếu bạn [đặc điểm], video này dành cho bạn'.",
  "Sinh 10 hook khẳng định táo bạo (bold claim) về hiệu quả của [sản phẩm].",
  "Viết 10 hook dạng 'thứ tôi ước mình biết sớm hơn về [chủ đề]'.",
  "Tạo 10 hook đặt ra một hiểu lầm phổ biến rồi hứa sẽ giải đáp về [chủ đề].",
  "Viết 10 hook dạng demo tức thì 'xem điều này xảy ra khi...' cho [sản phẩm].",
  "Sinh 10 hook nhắm nỗi sợ mua nhầm/mua hớ khi chọn [ngành hàng].",
  "Viết 10 hook dạng 'POV: bạn vừa phát hiện ra [sản phẩm]'.",
  "Tạo 10 hook dùng cấu trúc 'Stop! Đừng lướt nếu bạn...' cho [chủ đề].",
  "Viết 10 hook mở đầu bằng kết quả cuối cùng (result-first) rồi mới kể cách làm.",
  "Sinh 10 hook dạng thử thách 'tôi đã thử [X] trong 7 ngày và...'.",
  "Viết 10 hook tạo cảm giác độc quyền 'chỉ 1% người biết mẹo này về [chủ đề]'.",
  "Tạo 10 hook dạng phủ định trực giác (counter-intuitive) gây bất ngờ cho [ngành hàng].",
  "Viết 10 hook dạng 'giá của [sản phẩm] sẽ khiến bạn bất ngờ' (định hướng giá trị).",
  "Sinh 10 hook khai thác sự khan hiếm 'chỉ còn X suất/sản phẩm cuối'.",
  "Viết 10 hook dạng câu hỏi tu từ khiến người xem tự soi lại bản thân về [vấn đề].",
  "Tạo 10 hook 'tin hay không tùy bạn' về một sự thật liên quan [sản phẩm].",
  "Viết 10 hook mở màn bằng một con số review/lượt bán ấn tượng của [sản phẩm].",
  "Sinh 10 hook dạng 'đây là lý do bạn vẫn chưa [đạt được mong muốn]'.",
  "Viết 10 hook khai thác trend theo mùa (Tết/Hè/Sale) cho [sản phẩm].",
  "Tạo 10 hook dạng meme/hài hước bắt trend để mở video [sản phẩm].",
  "Viết 10 hook dùng phép so sánh cường điệu 'rẻ hơn cả ly trà sữa nhưng...'.",
  "Sinh 10 hook dạng 'bạn đang lãng phí tiền vào [thứ khác] trong khi...'.",
  "Viết 10 hook khơi gợi khát khao 'hình dung bạn có thể [lợi ích] mỗi ngày'.",
  "Tạo 10 hook dạng tiết lộ dần (teaser) khiến người xem xem hết để biết [bí mật].",
  "Viết 10 hook nhấn mạnh sự chuyển đổi 'từ [tệ] thành [tốt] chỉ nhờ [sản phẩm]'.",
  "Sinh 10 hook dạng 'câu trả lời cho câu hỏi ai cũng thắc mắc về [chủ đề]'.",
  "Viết 10 hook mở đầu bằng một tình huống oái oăm rất đời thường liên quan [vấn đề].",
  "Tạo 10 hook dạng 'xếp hạng' gây tranh luận: 'Top 1 [ngành hàng] đáng tiền nhất'.",
  "Viết 10 hook khai thác 'giá như tôi biết điều này trước khi mua [ngành hàng]'.",
  "Sinh 10 hook dạng lời mời thử thách khán giả 'bình luận nếu bạn cũng từng...'.",
  "Viết 10 hook cho video giáo dục biến kiến thức khô khan về [chủ đề] thành hấp dẫn.",
  "Tạo 10 hook dạng 'sự thật phũ phàng về [ngành hàng] mà người bán giấu bạn'.",
  "Viết 10 hook cực ngắn dưới 8 từ, đấm thẳng vào lợi ích cốt lõi của [sản phẩm].",
  "Sinh 10 hook dạng đối thoại nội tâm 'bạn có đang tự hỏi tại sao...' về [vấn đề].",
  "Viết 10 hook nhấn vào tiết kiệm thời gian/công sức nhờ [sản phẩm].",
  "Tạo 10 hook dạng before-after cực nhanh trong 3 giây cho [dịch vụ].",
  "Viết 10 hook khai thác tâm lý 'người khác đã có, còn bạn thì chưa' về [sản phẩm].",
  "Sinh 10 hook dùng câu điều kiện 'nếu... thì hãy dừng lại' cho tệp [khách hàng].",
  "Viết 10 hook dạng 'đừng tin quảng cáo, đây là sự thật về [sản phẩm]'.",
  "Tạo 10 hook mở đầu bằng một hành động lạ/bất ngờ để chặn lướt (pattern interrupt).",
  "Viết 10 hook dạng 'top câu hỏi khách hàng hỏi tôi nhiều nhất về [chủ đề]'.",
  "Sinh 10 hook khơi gợi sự nuối tiếc nếu bỏ lỡ ưu đãi [sản phẩm].",
  "Viết 10 hook dùng yếu tố quyền uy 'chuyên gia [lĩnh vực] khuyên bạn...'.",
  "Tạo 10 hook dạng 'thử đoán xem...' để tăng tương tác cho video [chủ đề].",
  "Viết 10 hook nhắm insight thầm kín của khách hàng ngành [ngành hàng].",
  "Sinh 10 hook dạng 'công thức/tỉ lệ vàng' mà ít người biết về [chủ đề].",
  "Viết 10 hook khai thác câu chuyện thất bại rồi thành công nhờ [sản phẩm].",
  "Tạo 10 hook dạng 'đây là điều tôi làm mỗi sáng/tối với [sản phẩm]'.",
  "Viết 10 hook cho ngành làm đẹp nhấn vào sự tự tin và thay đổi ngoại hình.",
  "Sinh 10 hook cho ngành mẹ & bé đánh trúng nỗi lo và tình thương của cha mẹ.",
  "Viết 10 hook cho ngành công nghệ nhấn vào 'nâng cấp cuộc sống/hiệu suất'.",
  "Tạo 10 hook cho ngành thời trang nhấn vào phong cách và giá trị đồng tiền.",
  "Viết 10 hook cho ngành F&B kích thích vị giác chỉ trong 3 giây đầu.",
  "Sinh 10 hook A/B test: 5 hook thiên cảm xúc và 5 hook thiên lý trí cho cùng [sản phẩm].",
  "Viết 10 hook kết hợp emoji và câu ngắn tối ưu cho caption đầu video [sản phẩm].",
  "Sinh 10 hook dạng 'điều tôi ước ai đó nói với tôi trước khi mua [ngành hàng]'.",
  "Viết 10 hook mở đầu bằng một sự thật gây tranh cãi rồi hứa chứng minh về [chủ đề].",
];

const image: string[] = [
  "Viết prompt tạo ảnh sản phẩm chuyên nghiệp cho [sản phẩm]: nền studio trắng, ánh sáng mềm, đổ bóng nhẹ, độ nét cao, 4K.",
  "Tạo prompt ảnh flatlay (chụp từ trên xuống) bố cục đẹp cho [sản phẩm] cùng phụ kiện liên quan, tông màu [màu].",
  "Viết prompt ảnh lifestyle: người dùng đang sử dụng [sản phẩm] trong bối cảnh [bối cảnh], ánh sáng tự nhiên, chân thực.",
  "Sinh 5 biến thể prompt ảnh nền cho poster khuyến mãi [sản phẩm], mỗi biến thể một phong cách màu khác nhau.",
  "Viết prompt ảnh sản phẩm 'levitation' (bay lơ lửng) với hiệu ứng khói/tia sáng cho [sản phẩm], nền tối sang trọng.",
  "Tạo prompt ảnh macro cận cảnh chất liệu và chi tiết tinh xảo của [sản phẩm], làm nổi bật sự cao cấp.",
  "Viết prompt ảnh mockup [sản phẩm] đặt trong khung cảnh thực tế (bàn làm việc/kệ bếp/phòng khách) để quảng cáo.",
  "Sinh prompt ảnh phong cách tối giản (minimalist) cho thương hiệu [thương hiệu]: nhiều khoảng trống, 1 sản phẩm trung tâm.",
  "Viết prompt ảnh banner ngang cho website bán [sản phẩm]: sản phẩm bên phải, chừa chỗ chữ bên trái, tông [màu].",
  "Tạo prompt ảnh nhân vật/người mẫu ảo mặc/dùng [sản phẩm], gương mặt tự nhiên, phù hợp thị trường Việt Nam.",
  "Viết prompt ảnh đồ ăn (food photography) cho [món ăn]: hấp dẫn, hơi nóng, plating đẹp, ánh sáng bên.",
  "Sinh prompt ảnh mùa lễ (Tết/Noel) trang trí lung linh có [sản phẩm] làm quà tặng trung tâm.",
  "Viết prompt ảnh so sánh before/after cho [dịch vụ] dạng ghép đôi, bố cục cân đối, cùng góc chụp.",
  "Tạo prompt ảnh 3D render sản phẩm [sản phẩm] siêu thực, phản chiếu, đổ bóng mềm, phông gradient.",
  "Viết prompt ảnh infographic quảng cáo nêu 3 lợi ích chính của [sản phẩm], icon tối giản, màu [màu].",
  "Sinh prompt ảnh nền pastel dễ thương cho ngành [ngành hàng] nhắm tệp khách nữ trẻ.",
  "Viết prompt ảnh sang trọng tông đen-vàng cho [sản phẩm cao cấp], ánh sáng viền, cảm giác đắt tiền.",
  "Tạo prompt ảnh outdoor: [sản phẩm] trong bối cảnh thiên nhiên (biển/núi/rừng) hợp với tính cách thương hiệu.",
  "Viết prompt ảnh 'hero shot' làm ảnh bìa chính cho chiến dịch [sản phẩm], ấn tượng ngay từ cái nhìn đầu.",
  "Sinh prompt ảnh phong cách UGC (do khách tự chụp bằng điện thoại) chân thực cho [sản phẩm], không quá bóng bẩy.",
  "Viết prompt ảnh cắt lớp/phân rã (exploded view) cho thấy cấu tạo bên trong [sản phẩm], nền trắng.",
  "Tạo prompt ảnh combo/set nhiều sản phẩm [sản phẩm] xếp gọn gàng, làm nổi bật giá trị trọn bộ.",
  "Viết prompt ảnh dạng meme/hài hước bám trend để quảng cáo [sản phẩm] trên mạng xã hội.",
  "Sinh prompt ảnh nền cho story/reels dọc 9:16 quảng bá [sản phẩm], chừa vùng an toàn cho chữ.",
  "Viết prompt ảnh 'ngày và đêm' hoặc '4 mùa' để thể hiện tính đa dụng của [sản phẩm].",
  "Tạo prompt ảnh phong cách vintage/retro cho [thương hiệu], hạt film, tông ám vàng hoài niệm.",
  "Viết prompt ảnh cyberpunk/neon cho [sản phẩm công nghệ], màu tím-xanh, ánh sáng tương lai.",
  "Sinh prompt ảnh chân dung khách hàng lý tưởng đang hạnh phúc sau khi dùng [sản phẩm].",
  "Viết prompt ảnh nền texture (vải, gỗ, đá cẩm thạch, bê tông) làm phông cho ảnh [sản phẩm].",
  "Tạo prompt ảnh 'size comparison' đặt [sản phẩm] cạnh vật quen thuộc để người xem hình dung kích thước.",
  "Viết prompt ảnh quảng cáo mỹ phẩm: kết cấu serum/kem mịn màng, giọt nước, làn da rạng rỡ, macro.",
  "Sinh prompt ảnh nhóm bạn/gia đình cùng trải nghiệm [sản phẩm], không khí vui vẻ, ấm áp.",
  "Viết prompt ảnh dạng 'ai nên dùng': ghép nhiều chân dung đa dạng đều phù hợp với [sản phẩm].",
  "Tạo prompt ảnh nền chuyển sắc (gradient) hiện đại làm backdrop cho thông điệp khuyến mãi [sản phẩm].",
  "Viết prompt ảnh chi tiết logo/nhãn thương hiệu [thương hiệu] nổi bật trên [sản phẩm], sắc nét.",
  "Sinh prompt ảnh phong cách Nhật Bản (wabi-sabi/zen) tối giản cho [sản phẩm], tinh tế, an nhiên.",
  "Viết prompt ảnh 'in use close-up' bàn tay đang cầm/thao tác với [sản phẩm], nhấn công thái học.",
  "Tạo prompt ảnh bộ sưu tập màu: cùng [sản phẩm] ở nhiều màu xếp thành dải, hấp dẫn thị giác.",
  "Viết prompt ảnh dạng 'catalogue' bố cục lưới đều cho nhiều mẫu [sản phẩm], thống nhất phong cách.",
  "Sinh prompt ảnh ánh sáng kịch tính (dramatic lighting) làm [sản phẩm] nổi bật trên nền tối.",
  "Viết prompt ảnh phong cách boho/thiên nhiên với cây xanh, gỗ, ánh nắng cho [sản phẩm].",
  "Tạo prompt ảnh mockup bao bì/hộp đựng [sản phẩm] đẹp mắt để khoe thiết kế đóng gói.",
  "Viết prompt ảnh 'splash' [đồ uống/mỹ phẩm] văng tung tóe đầy năng lượng, đóng băng chuyển động.",
  "Sinh prompt ảnh nền đơn sắc (single color) rực rỡ làm nổi bật [sản phẩm] tương phản.",
  "Viết prompt ảnh khung cảnh sang trọng (khách sạn, du thuyền, biệt thự) đặt [sản phẩm cao cấp] vào.",
  "Tạo prompt ảnh dạng 'quà tặng' [sản phẩm] gói ruy băng, thiệp, phù hợp chiến dịch tặng quà.",
  "Viết prompt ảnh thể thao/năng động với [sản phẩm], chuyển động, mồ hôi, năng lượng bùng nổ.",
  "Sinh prompt ảnh 'workspace aesthetic' bàn làm việc đẹp có [sản phẩm công nghệ], tông trung tính.",
  "Viết prompt ảnh cho ngành mẹ & bé: em bé/mẹ dùng [sản phẩm], mềm mại, an toàn, ấm áp.",
  "Tạo prompt ảnh dạng 'ingredient/nguyên liệu' bày quanh [sản phẩm] để chứng minh thành phần tự nhiên.",
  "Viết prompt ảnh poster sự kiện/khai trương có [sản phẩm], không khí lễ hội, pháo giấy, đèn.",
  "Sinh prompt ảnh phối cảnh nội thất có [sản phẩm gia dụng] hòa hợp không gian, đẹp như tạp chí.",
  "Viết prompt ảnh dạng 'trên tay' (hands-on) nhiều góc của [sản phẩm] cho bài review chi tiết.",
  "Tạo prompt ảnh phông trong suốt/PNG cho [sản phẩm] để dễ ghép vào thiết kế khác.",
  "Viết prompt ảnh mùa hè tươi mát (biển, trái cây, nước) quảng bá [sản phẩm mùa hè].",
  "Sinh prompt ảnh 'luxury unboxing' khoảnh khắc mở hộp [sản phẩm] sang trọng, ánh sáng ấm.",
  "Viết prompt ảnh so sánh 'hàng thật vs hàng giả' để dạy khách nhận biết [sản phẩm] chính hãng.",
  "Tạo prompt ảnh dạng banner đếm ngược sale với [sản phẩm] và khoảng trống cho con số %.",
  "Viết prompt ảnh phong cách hội họa (oil painting/watercolor) nghệ thuật cho [thương hiệu].",
  "Sinh prompt ảnh chân thực người Việt (gương mặt, bối cảnh nhà cửa) dùng [sản phẩm] cho ads bản địa.",
  "Viết prompt ảnh 'tính năng nổi bật' zoom vào một chi tiết công nghệ độc đáo của [sản phẩm].",
  "Tạo prompt ảnh nền động lực/thành công (đô thị, biểu đồ tăng) cho quảng cáo [khóa học/dịch vụ].",
  "Viết prompt ảnh dạng 'checklist/so sánh' trực quan giữa [sản phẩm] và đối thủ, thiên về ta.",
  "Sinh prompt ảnh tối ưu cho quảng cáo Facebook/Instagram feed (tỉ lệ 1:1) cho [sản phẩm].",
  "Viết prompt ảnh khung cảnh mưa/cozy trong nhà để quảng bá [sản phẩm] tạo cảm giác ấm cúng.",
  "Tạo prompt ảnh 'reveal' che một phần rồi hé lộ [sản phẩm mới], kích thích tò mò cho teaser.",
  "Viết prompt ảnh phong cách Y2K/gen-Z màu rực, sticker, vui nhộn cho [sản phẩm] tệp trẻ.",
  "Sinh prompt ảnh sản phẩm cùng review 5 sao và badge 'bán chạy' để tăng tin cậy thị giác.",
  "Viết prompt ảnh dạng 'bộ đôi hoàn hảo' ghép [sản phẩm A] với [sản phẩm B] để up-sell.",
  "Tạo prompt chỉnh sửa (edit) ảnh sản phẩm có sẵn: đổi nền, thêm ánh sáng, tăng độ nét, giữ nguyên sản phẩm.",
];

const review: string[] = [
  "Viết bài review chi tiết [sản phẩm] khoảng 400 chữ: ưu điểm, nhược điểm, ai nên mua, đánh giá sao, kèm CTA.",
  "Tạo dàn ý review video [sản phẩm] gồm 6 phần: mở, ngoại hình, tính năng, trải nghiệm, so sánh, kết luận.",
  "Viết review dạng 'thật lòng, không PR' về [sản phẩm], nêu cả 2 nhược điểm để tăng độ tin cậy.",
  "Viết bài so sánh [sản phẩm A] vs [sản phẩm B] theo 5 tiêu chí, kết luận nên chọn cái nào cho ai.",
  "Tạo bảng ưu — nhược điểm chi tiết của [sản phẩm] để chèn vào bài review hoặc caption.",
  "Viết review theo trải nghiệm cá nhân 'tôi đã dùng [sản phẩm] trong 30 ngày và đây là kết quả'.",
  "Viết review nhấn vào giá trị đồng tiền: '[sản phẩm] có đáng giá [X] không?', phân tích chi phí — lợi ích.",
  "Tạo review dạng hỏi đáp trả lời 5 câu người mua thường thắc mắc nhất về [sản phẩm].",
  "Viết review [sản phẩm] cho người mới bắt đầu: dễ dùng không, cần lưu ý gì, có phù hợp không.",
  "Viết review so sánh 3 mức giá của [ngành hàng] và định vị [sản phẩm] ở phân khúc nào đáng mua.",
  "Tạo review dạng 'unboxing + đánh giá nhanh' [sản phẩm]: cảm nhận mở hộp, chất lượng, phụ kiện.",
  "Viết review nhắm nỗi đau cụ thể: '[sản phẩm] có thực sự giải quyết [vấn đề] không?'.",
  "Viết review chuyên sâu về một tính năng nổi bật nhất của [sản phẩm] và tại sao nó đáng tiền.",
  "Tạo review tổng hợp 'top 3 [ngành hàng] đáng mua nhất', đặt [sản phẩm] ở vị trí số 1 kèm lý do.",
  "Viết review theo góc nhìn phản biện 'lý do bạn KHÔNG nên mua [sản phẩm]' rồi lật lại ai thì nên mua.",
  "Viết review [sản phẩm] cho tệp khách [chân dung khách hàng], nói đúng nhu cầu và ngữ cảnh của họ.",
  "Tạo review dạng checklist 'X điều cần kiểm tra trước khi mua [ngành hàng]' và [sản phẩm] đạt bao nhiêu.",
  "Viết review sau thời gian dài sử dụng: độ bền, xuống cấp, có nên mua lại [sản phẩm] không.",
  "Viết review kết hợp trải nghiệm giao hàng/đóng gói/dịch vụ khi mua [sản phẩm] online.",
  "Tạo review dạng 'kỳ vọng vs thực tế' khi mua [sản phẩm], trung thực và hài hước.",
  "Viết review chấm điểm chi tiết theo thang 10 cho từng khía cạnh của [sản phẩm], tổng kết điểm trung bình.",
  "Viết review dành cho quà tặng: '[sản phẩm] có phải món quà đáng tặng dịp [dịp] không?'.",
  "Tạo review so sánh [sản phẩm] chính hãng vs hàng nhái/rẻ hơn để khuyên chọn đúng.",
  "Viết review [sản phẩm] tập trung vào an toàn/thành phần/chất lượng cho tệp quan tâm sức khỏe.",
  "Viết review dạng câu chuyện: hành trình từ hoài nghi đến hài lòng với [sản phẩm].",
  "Tạo review nêu 3 tình huống sử dụng thực tế mà [sản phẩm] tỏa sáng.",
  "Viết review khách quan có dẫn thông số/số liệu để tăng tính thuyết phục cho [sản phẩm].",
  "Viết review dạng 'sau 1 tuần', 'sau 1 tháng', 'sau 3 tháng' dùng [sản phẩm], theo dõi diễn tiến.",
  "Tạo review so sánh [sản phẩm] với giải pháp truyền thống (cách cũ) mà mọi người hay dùng.",
  "Viết review cho ngành mỹ phẩm/skincare: kết cấu, mùi, độ thẩm thấu, hiệu quả sau [thời gian].",
  "Viết review cho ngành công nghệ: hiệu năng, pin, thiết kế, phần mềm, đáng tiền không, của [sản phẩm].",
  "Viết review cho ngành thời trang: chất vải, form dáng, độ bền, phối đồ, size, của [sản phẩm].",
  "Tạo review cho ngành F&B: hương vị, khẩu phần, giá, trải nghiệm, của [món ăn/quán].",
  "Viết review cho ngành gia dụng: độ tiện, tiết kiệm, độ ồn, vệ sinh, của [sản phẩm].",
  "Viết review dạng 'mua rồi có hối hận không?' tổng hợp cảm nhận thật về [sản phẩm].",
  "Tạo review nêu mẹo dùng [sản phẩm] hiệu quả hơn mà nhà sản xuất không nói.",
  "Viết review đối chiếu lời quảng cáo và thực tế: '[sản phẩm] có làm được như lời hứa?'.",
  "Viết review ngắn 3 câu súc tích cho caption bán hàng nhanh về [sản phẩm].",
  "Tạo review dài chuẩn SEO cho blog về [sản phẩm], có tiêu đề phụ, từ khóa [từ khóa], CTA.",
  "Viết review dạng 'dành cho người bận rộn': tóm tắt nhanh có nên mua [sản phẩm] hay không trong 30 giây.",
  "Viết review đánh giá dịch vụ hậu mãi/bảo hành của [thương hiệu] khi mua [sản phẩm].",
  "Tạo review tổng hợp phản hồi của nhiều người dùng khác về [sản phẩm], khách quan đa chiều.",
  "Viết review 'nâng cấp có đáng không?': so sánh [sản phẩm đời mới] với [sản phẩm đời cũ].",
  "Viết review nhắm người đang phân vân giữa [sản phẩm] và không mua gì cả, thúc đẩy quyết định.",
  "Tạo review dạng infographic bằng chữ: liệt kê thông số + đánh giá + giá + link mua [sản phẩm].",
  "Viết review [sản phẩm] theo phong cách chuyên gia có kinh nghiệm trong ngành [ngành hàng].",
  "Viết review khai thác một lỗi/nhược điểm và cách khắc phục để người mua yên tâm về [sản phẩm].",
  "Tạo review so sánh trải nghiệm mua [sản phẩm] ở các nền tảng (Shopee/Lazada/TikTok Shop).",
  "Viết review dạng 'đáng đồng tiền bát gạo' nhấn ROI/tiết kiệm dài hạn khi dùng [sản phẩm].",
  "Viết review [sản phẩm] dành riêng cho dân văn phòng/sinh viên/mẹ bỉm — chọn 1 tệp và nói đúng insight.",
  "Tạo review dạng 'điểm cộng — điểm trừ — kết luận' gọn cho video TikTok 40 giây về [sản phẩm].",
  "Viết review so sánh cảm giác dùng [sản phẩm] lúc mới mua và sau khi đã quen, có gì thay đổi.",
  "Viết review nêu rõ '[sản phẩm] hợp với ai, không hợp với ai' để lọc đúng khách.",
  "Tạo review kèm 5 câu hỏi thường gặp và trả lời ngắn gọn để chèn cuối bài về [sản phẩm].",
  "Viết review dạng 'thử thách người thân dùng [sản phẩm]' và tổng hợp nhận xét của họ.",
  "Viết review trung thực về giá: '[sản phẩm] đắt hay rẻ so với chất lượng?', phân tích rõ ràng.",
  "Tạo review dạng bảng so sánh 4 sản phẩm cùng tầm giá trong [ngành hàng] và gợi ý lựa chọn.",
  "Viết review nhấn vào cảm xúc: '[sản phẩm] đã thay đổi thói quen/cuộc sống của tôi thế nào'.",
  "Viết review đánh giá tính đáng tin của thương hiệu [thương hiệu] dựa trên trải nghiệm [sản phẩm].",
  "Tạo review dạng 'tôi đã mua nhầm — và đây là cái đáng mua hơn', dẫn dắt tới [sản phẩm].",
  "Viết review [sản phẩm] tối ưu để đặt kèm link Affiliate, có lời kêu gọi nhấp mượt mà, không lộ liễu.",
  "Viết review cập nhật 'sau khi giá giảm/lên sale, [sản phẩm] có còn đáng mua không'.",
  "Tạo review dạng phỏng vấn nhanh 3 người dùng [sản phẩm] với 3 mức độ hài lòng khác nhau.",
  "Viết review tổng kết cuối năm 'sản phẩm [ngành hàng] tôi tâm đắc nhất' và lý do đó là [sản phẩm].",
  "Viết review khai thác một hiểu lầm phổ biến về [sản phẩm] rồi làm rõ sự thật cho người mua.",
  "Tạo review dạng 'giá này mua được gì' liệt kê trọn bộ những gì khách nhận khi mua [sản phẩm].",
  "Viết review [sản phẩm] cho người quan tâm bền vững/thân thiện môi trường, nhấn giá trị xanh.",
  "Viết review so sánh [sản phẩm] tự dùng vs được tặng, cảm nhận về giá trị thực khách quan.",
  "Tạo bộ 5 câu 'chốt review' mạnh mẽ để kết bài, thúc đẩy hành động mua [sản phẩm] ngay.",
  "Viết review dạng 'thử trong 24h': cảm nhận ngay lập tức khi mới dùng [sản phẩm], nóng hổi và chân thực.",
];

const shopee: string[] = [
  "Viết caption bán hàng Shopee Affiliate cho [sản phẩm]: hook, 3 lợi ích, ưu đãi, CTA nhấp link, kèm hashtag.",
  "Tạo 5 tiêu đề sản phẩm chuẩn SEO Shopee cho [sản phẩm] chứa từ khóa [từ khóa] và thu hút nhấp.",
  "Viết kịch bản video review Shopee Affiliate 30 giây cho [sản phẩm], khéo léo dẫn tới link giỏ hàng.",
  "Viết bài đăng giới thiệu [sản phẩm] cho nhóm/Facebook kèm link Shopee Affiliate, giọng chia sẻ chân thật.",
  "Tạo 10 hashtag hiệu quả cho bài Shopee Affiliate ngành [ngành hàng] để tăng tiếp cận.",
  "Viết nội dung 'flash sale hôm nay' cho [sản phẩm] trên Shopee, tạo cảm giác khẩn cấp và khan hiếm.",
  "Tạo bài so sánh 3 sản phẩm cùng loại trên Shopee, khuyên chọn [sản phẩm] kèm link Affiliate.",
  "Viết caption dạng 'săn deal' tổng hợp 5 món ngành [ngành hàng] đáng mua trên Shopee, mỗi món 1 dòng chốt.",
  "Tạo kịch bản livestream Shopee bán [sản phẩm]: chào — demo — ưu đãi — mã giảm — chốt đơn — nhắc giỏ.",
  "Viết bài blog review chuẩn SEO nhắm từ khóa '[từ khóa] tốt nhất' và gắn link Affiliate [sản phẩm].",
  "Tạo 5 mẫu bình luận hữu ích để chèn link Affiliate [sản phẩm] một cách tự nhiên dưới video/bài viết.",
  "Viết caption khai thác mã giảm giá/hoàn xu Shopee cho [sản phẩm], hướng dẫn cách săn ưu đãi.",
  "Tạo nội dung 'giỏ hàng của tôi tháng này' review nhanh 5 món kèm link Shopee Affiliate.",
  "Viết bài 'đánh giá thật sau khi mua [sản phẩm] trên Shopee' để tăng tin cậy trước khi gắn link.",
  "Tạo tiêu đề + mô tả ngắn hấp dẫn cho bài ghim (pin) sản phẩm [sản phẩm] trên Shopee.",
  "Viết caption dạng 'must-have' cho [chân dung khách hàng] gồm 3 món Shopee thiết yếu và lý do.",
  "Tạo kịch bản video 'mở hộp đơn Shopee' [sản phẩm], review nhanh và kêu gọi mua qua link.",
  "Viết nội dung so sánh giá [sản phẩm] giữa các shop trên Shopee và gợi ý shop uy tín nhất.",
  "Tạo 5 câu chốt đơn thúc đẩy nhấp link Affiliate cho [sản phẩm] mà không gây khó chịu.",
  "Viết bài 'top sản phẩm dưới [X] đồng đáng mua trên Shopee' cho ngành [ngành hàng].",
  "Tạo caption theo mùa sale lớn (9.9, 11.11, 12.12) cho [sản phẩm], nhấn ưu đãi cực sốc.",
  "Viết nội dung hướng dẫn 'cách chọn [ngành hàng] trên Shopee không bị hớ', dẫn tới [sản phẩm] gợi ý.",
  "Tạo bài đăng dạng 'review có tâm' nêu ưu nhược [sản phẩm] rồi đặt link Affiliate cuối bài.",
  "Viết caption ngắn dưới 150 ký tự cho ảnh sản phẩm [sản phẩm] kèm CTA nhấp link Shopee.",
  "Tạo kịch bản Reels/TikTok 'điểm 5 món Shopee tôi ưng nhất tháng này' ngành [ngành hàng].",
  "Viết bài 'giải cứu ví tiền' review sản phẩm giá rẻ mà chất lượng [sản phẩm] trên Shopee.",
  "Tạo 3 biến thể caption A/B test cho cùng [sản phẩm]: 1 cảm xúc, 1 lý trí, 1 hài hước.",
  "Viết nội dung tư vấn 'nên mua [sản phẩm A] hay [sản phẩm B] trên Shopee', kèm 2 link Affiliate.",
  "Tạo bài đăng khai thác đánh giá 5 sao và lượt bán cao của [sản phẩm] để tạo hiệu ứng đám đông.",
  "Viết caption dạng 'mẹo mua sắm Shopee thông minh' và lồng ghép [sản phẩm] như ví dụ điển hình.",
  "Tạo kịch bản video 'thử [sản phẩm] mua trên Shopee — đáng tiền không?' có twist cuối.",
  "Viết bài tổng hợp 'wishlist Shopee' theo chủ đề [chủ đề], mỗi món 1 lý do nên thêm vào giỏ.",
  "Tạo caption nhắm dịp [dịp lễ] gợi ý quà tặng [sản phẩm] mua trên Shopee kèm link.",
  "Viết nội dung 'hàng nội địa/chính hãng trên Shopee': cách phân biệt và gợi ý shop cho [sản phẩm].",
  "Tạo 5 hook mở đầu riêng cho video Affiliate Shopee ngành [ngành hàng] để chặn lướt.",
  "Viết bài 'tôi đã tiết kiệm [X] nhờ mua [sản phẩm] đúng đợt sale Shopee', chia sẻ mẹo thật.",
  "Tạo kịch bản 'haul Shopee' khoe nhiều món vừa mua, review nhanh từng món kèm link.",
  "Viết caption cho combo/bundle [sản phẩm A] + [sản phẩm B] trên Shopee, nhấn tiết kiệm khi mua chung.",
  "Tạo nội dung dạng 'câu hỏi thường gặp khi mua [sản phẩm] trên Shopee' và giải đáp ngắn gọn.",
  "Viết bài review dài chuẩn để đăng blog/website Affiliate, chèn 2-3 link [sản phẩm] tự nhiên.",
  "Tạo caption dạng story: 'mình từng mua nhầm, giờ mách bạn [sản phẩm] xịn hơn trên Shopee'.",
  "Viết kịch bản video 'unbox + test' [sản phẩm] và điều hướng người xem bấm giỏ hàng ngay.",
  "Tạo bài đăng cho ngành làm đẹp: 'skincare/makeup Shopee dưới [X] đồng' kèm [sản phẩm] và link.",
  "Viết caption cho ngành gia dụng: 'món nhỏ nhưng có võ' review [sản phẩm] tiện ích trên Shopee.",
  "Tạo bài cho ngành mẹ & bé: 'đồ cho bé mẹ bỉm nên sắm trên Shopee', gợi ý [sản phẩm].",
  "Viết nội dung cho ngành thời trang: 'phối đồ với [sản phẩm] Shopee', kèm link mua nhanh.",
  "Tạo caption cho ngành công nghệ/phụ kiện: 'gadget đáng tiền trên Shopee', review [sản phẩm].",
  "Viết bài 'checklist mua sắm Shopee ngày sale', chèn [sản phẩm] vào danh sách nên mua.",
  "Tạo kịch bản video so sánh 'kỳ vọng vs thực tế' khi mua [sản phẩm] Shopee, chân thực và vui.",
  "Viết caption khai thác tâm lý 'giá này chỉ có hôm nay' cho [sản phẩm] trong đợt flash sale Shopee.",
  "Tạo nội dung hướng dẫn cách dùng link Affiliate/mã giới thiệu để người mua ủng hộ bạn khi mua [sản phẩm].",
  "Viết bài dạng 'best seller Shopee tuần này' ngành [ngành hàng], phân tích vì sao [sản phẩm] hot.",
  "Tạo caption cho ảnh flatlay nhiều món Shopee theo tông màu [màu], gắn link từng món.",
  "Viết kịch bản 'review 1 tháng dùng [sản phẩm] mua trên Shopee' để tạo nội dung dài, đáng tin.",
  "Tạo 5 câu CTA khác nhau kêu gọi 'bấm link ở giỏ hàng/bio' cho video Affiliate [sản phẩm].",
  "Viết nội dung 'so sánh mua [sản phẩm] trên Shopee vs mua ngoài tiệm', nhấn tiện lợi và giá.",
  "Tạo bài đăng dạng 'đồ tôi mua đi mua lại nhiều lần trên Shopee', đề xuất [sản phẩm] tin dùng.",
  "Viết caption ngắn kích thích tò mò cho video [sản phẩm] Shopee, để CTA link ở bình luận đầu tiên.",
  "Tạo kịch bản video 'top deal hời nhất Shopee hôm nay' điểm nhanh 5 món kèm giá và link.",
  "Viết bài tư vấn chọn size/màu/phiên bản [sản phẩm] khi mua trên Shopee để giảm đổi trả.",
  "Tạo nội dung 'mua [sản phẩm] hoàn xu Shopee': hướng dẫn tối ưu ưu đãi để mua rẻ nhất.",
  "Viết caption định vị bạn là 'người review có tâm' để xây niềm tin dài hạn cho kênh Affiliate.",
  "Tạo bài đăng khai thác feedback khách đã mua [sản phẩm] qua link của bạn, tạo bằng chứng xã hội.",
  "Viết kịch bản video 'giới thiệu shop uy tín trên Shopee' cho [ngành hàng], gắn [sản phẩm] tiêu biểu.",
  "Tạo caption dạng 'đừng bỏ lỡ' cho [sản phẩm] sắp hết hàng/sắp tăng giá trên Shopee.",
  "Viết nội dung tổng kết 'những món Shopee đáng tiền nhất tôi từng mua', dẫn tới [sản phẩm].",
  "Tạo bộ 3 caption theo 3 nền tảng (Facebook, TikTok, Threads) cho cùng link Affiliate [sản phẩm].",
  "Viết bài 'cách kiếm tiền với Shopee Affiliate cho người mới' và ví dụ chọn [sản phẩm] dễ bán.",
  "Tạo caption chốt hạ cuối chiến dịch, tổng hợp lý do và kêu gọi mua [sản phẩm] qua link ngay hôm nay.",
  "Viết bài 'kinh nghiệm 1 năm làm Shopee Affiliate': mẹo chọn [ngành hàng] dễ ra đơn và cách tăng hoa hồng.",
];

const tiktok: string[] = [
  "Viết caption TikTok viral cho video bán [sản phẩm]: hook đầu dòng, giá trị, CTA, kèm 5 hashtag xu hướng.",
  "Tạo 10 ý tưởng video TikTok cho [sản phẩm] bám các định dạng đang viral (POV, GRWM, storytime...).",
  "Viết kịch bản TikTok 20 giây bắt trend [trend] và lồng [sản phẩm] tự nhiên, không gượng ép.",
  "Tạo lịch nội dung TikTok 7 ngày cho kênh bán [ngành hàng], mỗi ngày một dạng video khác nhau.",
  "Viết 10 hook mở đầu 3 giây tối ưu cho thuật toán TikTok về chủ đề [chủ đề].",
  "Tạo ý tưởng video TikTok dạng 'storytime' kể trải nghiệm với [sản phẩm] khiến người xem xem hết.",
  "Viết kịch bản TikTok 'GRWM (get ready with me)' lồng ghép [sản phẩm] vào thói quen buổi sáng.",
  "Tạo 5 concept video TikTok 'trước — sau' cho [dịch vụ/sản phẩm] gây hiệu ứng wow.",
  "Viết caption + hashtag cho video TikTok Shop bán [sản phẩm] để tối ưu hiển thị và giỏ hàng.",
  "Tạo ý tưởng series TikTok nhiều tập (part 1, 2, 3...) xoay quanh [chủ đề] để giữ chân người theo dõi.",
  "Viết kịch bản TikTok dạng 'POV: bạn vừa tìm ra [sản phẩm] thay đổi cuộc chơi'.",
  "Tạo 10 tiêu đề/text overlay ngắn gây tò mò để đặt trên video TikTok về [sản phẩm].",
  "Viết ý tưởng video TikTok 'thử thách' liên quan [sản phẩm] dễ lan truyền và kêu gọi bắt trend.",
  "Tạo kịch bản TikTok hài/skit tình huống đời thường có [sản phẩm] xuất hiện đúng lúc.",
  "Viết caption TikTok khai thác FOMO cho đợt sale [sản phẩm], nhấn số lượng có hạn.",
  "Tạo 5 ý tưởng video TikTok dạng 'reply comment' để trả lời thắc mắc và bán thêm [sản phẩm].",
  "Viết kịch bản TikTok 'day in the life' của [nghề nghiệp/chân dung] có dùng [sản phẩm].",
  "Tạo bộ hashtag TikTok phân tầng (rộng — ngách — thương hiệu) cho video ngành [ngành hàng].",
  "Viết ý tưởng video TikTok 'unboxing ASMR' [sản phẩm] tận dụng âm thanh để giữ chân.",
  "Tạo kịch bản TikTok theo cấu trúc 'vấn đề — twist — giải pháp [sản phẩm]' trong 15 giây.",
  "Viết 10 câu CTA cuối video TikTok kêu gọi bấm giỏ hàng/theo dõi cho kênh bán [sản phẩm].",
  "Tạo ý tưởng video TikTok 'ranking/xếp hạng' các [ngành hàng] gây tranh luận để tăng bình luận.",
  "Viết kịch bản TikTok dùng âm thanh trend (trending sound) và khớp nội dung [sản phẩm] theo beat.",
  "Tạo 5 concept video TikTok 'green screen' phản ứng với bài viết/tin tức liên quan [chủ đề].",
  "Viết ý tưởng video TikTok 'tips nhanh' 3 mẹo về [chủ đề] mà [sản phẩm] hỗ trợ.",
  "Tạo kịch bản TikTok 'reveal' che sản phẩm rồi hé lộ ở giây cuối để giữ người xem đến hết.",
  "Viết caption TikTok kể chuyện thương hiệu [thương hiệu] ngắn gọn, cảm xúc, kèm CTA nhẹ nhàng.",
  "Tạo 10 ý tưởng hook text để test tỉ lệ giữ chân 3 giây đầu cho video [sản phẩm].",
  "Viết kịch bản TikTok 'so sánh giá/chất lượng' [sản phẩm] vs đối thủ, khách quan mà nghiêng về ta.",
  "Tạo ý tưởng video TikTok 'transition' sáng tạo để chuyển từ vấn đề sang [sản phẩm] mượt mà.",
  "Viết ý tưởng nội dung TikTok nuôi kênh 'giá trị trước, bán sau' cho ngách [ngách], gồm 10 chủ đề.",
  "Tạo kịch bản TikTok 'phản ứng thật' của người dùng lần đầu trải nghiệm [sản phẩm].",
  "Viết caption TikTok tối ưu từ khóa tìm kiếm (TikTok SEO) cho video về [sản phẩm].",
  "Tạo ý tưởng video TikTok 'myth busting' phá bỏ lầm tưởng về [ngành hàng] để định vị [sản phẩm].",
  "Viết kịch bản TikTok 'checklist' đếm các tiêu chí chọn [ngành hàng], kết bằng [sản phẩm] đạt hết.",
  "Tạo 5 ý tưởng video TikTok theo dịp [dịp lễ] gắn với nhu cầu mua [sản phẩm].",
  "Viết ý tưởng video TikTok 'duet/stitch' với nội dung có sẵn để chèn quan điểm và [sản phẩm].",
  "Tạo kịch bản TikTok 'tôi đã thử [sản phẩm] viral và đây là sự thật', giữ suspense đến cuối.",
  "Viết caption TikTok dạng câu hỏi mở để tăng bình luận cho video [chủ đề].",
  "Tạo ý tưởng video TikTok 'bộ sưu tập/haul' khoe nhiều mẫu [sản phẩm] và review nhanh.",
  "Viết kịch bản TikTok 'mini tutorial' hướng dẫn dùng [sản phẩm] trong 3 bước, có số thứ tự.",
  "Tạo 10 ý tưởng nội dung TikTok cho kênh cá nhân xây thương hiệu quanh ngách [ngách].",
  "Viết caption TikTok cực ngắn kiểu 'less is more' để nhường sân cho video [sản phẩm] tự nói.",
  "Tạo kịch bản TikTok 'trend nhảy/điệu bộ' đang hot, khéo chèn [sản phẩm] vào khung hình.",
  "Viết ý tưởng video TikTok 'oddly satisfying' với [sản phẩm] để tăng thời lượng xem.",
  "Tạo 5 biến thể caption TikTok A/B test cho cùng [sản phẩm]: cảm xúc, tò mò, thẳng thắn, hài, giá trị.",
  "Viết kịch bản TikTok 'behind the scenes' quá trình làm/đóng gói [sản phẩm] tạo niềm tin.",
  "Tạo ý tưởng video TikTok 'trả lời tin nhắn khách hàng' để xử lý phản đối và bán [sản phẩm].",
  "Viết caption TikTok gắn CTA điều hướng qua bio/link để mua [sản phẩm] mà không vi phạm nền tảng.",
  "Tạo kịch bản TikTok dạng 'lời khuyên gan ruột' cho người mới trong [lĩnh vực], dẫn tới [sản phẩm].",
  "Viết 10 ý tưởng video TikTok theo insight/nỗi đau khác nhau của tệp khách [ngành hàng].",
  "Tạo ý tưởng video TikTok 'giá trị sốc' tiết lộ mẹo miễn phí rồi upsell [sản phẩm].",
  "Viết kịch bản TikTok 'so sánh tôi ngày xưa vs bây giờ' nhờ [sản phẩm], hành trình chuyển đổi.",
  "Tạo caption TikTok theo phong cách gen-Z (ngắn, chất, có meme) cho [sản phẩm] tệp trẻ.",
  "Viết ý tưởng video TikTok livestream nhắc lịch: teaser trước giờ live bán [sản phẩm].",
  "Tạo kịch bản TikTok '3 lý do bạn nên mua [sản phẩm] ngay hôm nay' nhịp nhanh, dứt khoát.",
  "Viết bộ 10 hashtag + 3 caption mẫu để đăng đều đặn cho kênh TikTok bán [ngành hàng].",
  "Tạo ý tưởng nội dung TikTok 'trend dự đoán' để đón đầu xu hướng ngành [ngành hàng].",
  "Viết kịch bản TikTok kết hợp kể chuyện khách hàng thật + demo [sản phẩm] + CTA trong 30 giây.",
  "Tạo bảng phân tích 'vì sao video [chủ đề] này viral' và cách áp dụng cho kênh bán [sản phẩm].",
  "Viết ý tưởng video TikTok 'so kè' 2 lựa chọn để khán giả bình luận chọn phe, tăng tương tác cho [sản phẩm].",
  "Tạo kịch bản TikTok mở màn bằng con số/kết quả gây sốc rồi giải thích nhờ [sản phẩm].",
  "Viết caption TikTok tạo cảm giác cộng đồng 'ai cũng đang dùng [sản phẩm], còn bạn?'.",
  "Tạo 10 ý tưởng video ngắn để tái sử dụng (repurpose) 1 nội dung [sản phẩm] thành nhiều clip.",
  "Viết kịch bản TikTok 'reply comment hỏi giá' vừa báo giá vừa nhấn giá trị để chốt đơn [sản phẩm].",
];

export const promptCategories: PromptCategory[] = [
  {
    slug: "video-ai",
    title: "Prompt làm Video AI",
    emoji: "🎬",
    desc: "Tạo video quảng cáo, review, b-roll bằng công cụ AI (Runway, Kling, Veo...).",
    prompts: videoAI,
  },
  {
    slug: "kich-ban",
    title: "Prompt viết Kịch bản",
    emoji: "📝",
    desc: "Kịch bản bán hàng, review, livestream, quảng cáo theo công thức AIDA/PAS.",
    prompts: script,
  },
  {
    slug: "hook",
    title: "Prompt viết Hook",
    emoji: "🎣",
    desc: "Câu mở đầu 3 giây chặn lướt, tăng giữ chân và lượt xem.",
    prompts: hook,
  },
  {
    slug: "tao-anh",
    title: "Prompt tạo Ảnh",
    emoji: "🖼️",
    desc: "Ảnh sản phẩm, lifestyle, poster, banner bằng Midjourney/DALL·E/Flux...",
    prompts: image,
  },
  {
    slug: "review-san-pham",
    title: "Prompt review Sản phẩm",
    emoji: "⭐",
    desc: "Bài & video review chuyển đổi cao, so sánh, đánh giá thuyết phục.",
    prompts: review,
  },
  {
    slug: "shopee-affiliate",
    title: "Prompt Shopee Affiliate",
    emoji: "🛒",
    desc: "Caption, kịch bản, bài đăng chốt đơn và điều hướng link tiếp thị liên kết.",
    prompts: shopee,
  },
  {
    slug: "tiktok",
    title: "Prompt TikTok",
    emoji: "📱",
    desc: "Ý tưởng, kịch bản, caption, hashtag bắt trend cho kênh TikTok bán hàng.",
    prompts: tiktok,
  },
];

export const totalPrompts = promptCategories.reduce(
  (sum, c) => sum + c.prompts.length,
  0,
);
